distancia = int(input("Digite uma distância em metros: "))
print("Distancia em KM:", distancia/1000)
print("Distancia em HM:", distancia/100)
print("Distancia em DAM:", distancia/10)
print("Distancia em DM:", distancia*10)
print("Distancia em CM:", distancia*100)
print("Distancia em MM:", distancia*1000)