numero = int(input("Digite um numero para ver sua tabuada: "))
print("-"*30)
print("{} x 1  = {}".format(numero, 1*numero))
print("{} x 2  = {}".format(numero, 2*numero))
print("{} x 3  = {}".format(numero, 3*numero))
print("{} x 4  = {}".format(numero, 4*numero))
print("{} x 5  = {}".format(numero, 5*numero))
print("{} x 6  = {}".format(numero, 6*numero))
print("{} x 7  = {}".format(numero, 7*numero))
print("{} x 8  = {}".format(numero, 8*numero))
print("{} x 9  = {}".format(numero, 9*numero))
print("{} x 10 = {}".format(numero, 10*numero))
print("-"*30)
